[package]
name = "skyl-data"
version = "0.1.0"
edition = "2024"

[dependencies]
num_enum = "0.7.3"
serde = { version = "1.0", features = ["derive", "rc"] }
bincode = { version = "2.0.1", features = ["serde", "derive"] }
aes-gcm = "0.10"
aes = "0.8"
aead = "0.5"
rand = "0.9.2"
